// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'radio_station.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

RadioStation _$RadioStationFromJson(Map<String, dynamic> json) => RadioStation(
      changeuuid: json['changeuuid'] as String?,
      stationuuid: json['stationuuid'] as String?,
      serveruuid: json['serveruuid'] as String?,
      name: json['name'] as String?,
      url: json['url'] as String?,
      urlResolved: json['url_resolved'] as String?,
      homepage: json['homepage'] as String?,
      favicon: json['favicon'] as String?,
      tags: json['tags'] as String?,
      country: json['country'] as String?,
      countrycode: json['countrycode'] as String?,
      iso31662: json['iso31662'],
      state: json['state'] as String?,
      language: json['language'] as String?,
      languagecodes: json['languagecodes'] as String?,
      votes: json['votes'] as int?,
      lastchangetime: json['lastchangetime'] as String?,
      lastchangetimeIso8601: json['lastchangetime_iso8601'] as String?,
      codec: json['codec'] as String?,
      bitrate: json['bitrate'] as int?,
      hls: json['hls'] as int?,
      lastcheckok: json['lastcheckok'] as int?,
      lastchecktime: json['lastchecktime'] as String?,
      lastchecktimeIso8601: json['lastchecktime_iso8601'] as String?,
      lastcheckoktime: json['lastcheckoktime'] as String?,
      lastcheckoktimeIso8601: json['lastcheckoktime_iso8601'] as String?,
      lastlocalchecktime: json['lastlocalchecktime'] as String?,
      lastlocalchecktimeIso8601: json['lastlocalchecktime_iso8601'] as String?,
      clicktimestamp: json['clicktimestamp'] as String?,
      clicktimestampIso8601: json['clicktimestamp_iso8601'] as String?,
      clickcount: json['clickcount'] as int?,
      clicktrend: json['clicktrend'] as int?,
      sslError: json['ssl_error'] as int?,
      geoLat: json['geo_lat'],
      geoLong: json['geo_long'],
      hasExtendedInfo: json['has_extended_info'] as bool?,
    );

Map<String, dynamic> _$RadioStationToJson(RadioStation instance) =>
    <String, dynamic>{
      'changeuuid': instance.changeuuid,
      'stationuuid': instance.stationuuid,
      'serveruuid': instance.serveruuid,
      'name': instance.name,
      'url': instance.url,
      'url_resolved': instance.urlResolved,
      'homepage': instance.homepage,
      'favicon': instance.favicon,
      'tags': instance.tags,
      'country': instance.country,
      'countrycode': instance.countrycode,
      'iso31662': instance.iso31662,
      'state': instance.state,
      'language': instance.language,
      'languagecodes': instance.languagecodes,
      'votes': instance.votes,
      'lastchangetime': instance.lastchangetime,
      'lastchangetime_iso8601': instance.lastchangetimeIso8601,
      'codec': instance.codec,
      'bitrate': instance.bitrate,
      'hls': instance.hls,
      'lastcheckok': instance.lastcheckok,
      'lastchecktime': instance.lastchecktime,
      'lastchecktime_iso8601': instance.lastchecktimeIso8601,
      'lastcheckoktime': instance.lastcheckoktime,
      'lastcheckoktime_iso8601': instance.lastcheckoktimeIso8601,
      'lastlocalchecktime': instance.lastlocalchecktime,
      'lastlocalchecktime_iso8601': instance.lastlocalchecktimeIso8601,
      'clicktimestamp': instance.clicktimestamp,
      'clicktimestamp_iso8601': instance.clicktimestampIso8601,
      'clickcount': instance.clickcount,
      'clicktrend': instance.clicktrend,
      'ssl_error': instance.sslError,
      'geo_lat': instance.geoLat,
      'geo_long': instance.geoLong,
      'has_extended_info': instance.hasExtendedInfo,
    };
